/*
 * This file is part of FlyCat.
 *
 * FlyCat is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Copyright (c)  YumeYucca 2025 - Present
 * Based on YumeBox by YumeYucca
 *
 */

package com.github.lmfirefly.flycat.runtime.service.profile

import android.content.Context
import androidx.work.Constraints
import androidx.work.CoroutineWorker
import androidx.work.Data
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.NetworkType
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkerParameters
import androidx.work.WorkManager
import com.github.lmfirefly.flycat.core.Clash
import com.github.lmfirefly.flycat.core.importedDir
import com.github.lmfirefly.flycat.core.model.FetchStatus
import com.github.lmfirefly.flycat.core.model.profile.Imported
import com.github.lmfirefly.flycat.core.model.profile.Profile
import com.github.lmfirefly.flycat.runtime.api.remote.IFetchObserver
import com.github.lmfirefly.flycat.runtime.service.config.ServiceStore
import com.github.lmfirefly.flycat.runtime.service.records.ImportedDao
import com.github.lmfirefly.flycat.runtime.service.records.SelectionDao
import com.github.lmfirefly.flycat.runtime.service.util.Log
import com.github.lmfirefly.flycat.runtime.service.util.sendProfileChanged
import java.io.File
import java.util.UUID
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import timber.log.Timber

object ProfileProcessor {
    private val profileLock = Mutex()
    private val processLock = Mutex()

    private data class SubscriptionInfo(
        val upload: Long? = null,
        val download: Long? = null,
        val total: Long? = null,
        val expire: Long? = null,
        val title: String? = null,
        val filename: String? = null,
        val updateInterval: Long? = null,
    )

    private data class UpdateSnapshot(
        val imported: Imported,
        val hasCommittedConfig: Boolean,
    )

    private fun FetchStatus.toSubscriptionInfo(): SubscriptionInfo? {
        if (action != FetchStatus.Action.SubscriptionInfo) return null
        return SubscriptionInfo(
            upload = subUpload,
            download = subDownload,
            total = subTotal,
            expire = subExpire,
            title = subTitle,
            filename = subFilename,
            updateInterval = subUpdateInterval,
        )
    }

    private fun resolveSubscriptionName(
        snapshotName: String,
        snapshotSource: String,
        subInfo: SubscriptionInfo?,
    ): String {
        if (!ProfileNameUtils.isAutoGeneratedProfileName(snapshotName)) return snapshotName

        val headerTitle = subInfo?.title?.takeIf { it.isNotBlank() }
        val filename = subInfo?.filename?.substringBeforeLast(".")?.takeIf { it.isNotBlank() }
        val sourceName = ProfileNameUtils.extractSourceBaseName(snapshotSource)

        if (headerTitle != null) return headerTitle
        if (filename != null) return filename
        if (sourceName != null) return sourceName
        return snapshotName
    }

    @Suppress("TooGenericExceptionCaught")
    suspend fun update(context: Context, uuid: UUID, callback: IFetchObserver?) {
        withContext(Dispatchers.IO + NonCancellable) {
            processLock.withLock {
                val targetDir = context.importedDir.resolve(uuid.toString())
                val stagingDir =
                    context.noBackupFilesDir.resolve("profile-staging").resolve(uuid.toString())
                val snapshot = profileLock.withLock {
                    val imported =
                        ImportedDao.queryByUUID(uuid)
                            ?: throw IllegalArgumentException("profile $uuid not found")

                    stagingDir.deleteRecursively()
                    stagingDir.mkdirs()

                    if (targetDir.exists()) {
                        targetDir.copyRecursively(stagingDir, overwrite = true)
                    }

                    UpdateSnapshot(
                        imported = imported,
                        // Sentinel for "this profile has already committed a config", used below to decide whether a failed update may roll back (delete) the profile.
                        // The source profile file is config.yaml (written by fetchAndValid on a successful fetch); runtime.yaml is no longer produced by any path, so it can never serve as this sentinel.
                        hasCommittedConfig = targetDir.resolve("config.yaml").isFile,
                    )
                }

                var cb = callback
                var subInfo: SubscriptionInfo? = null

                try {
                    Clash.setAgeSecretKey(snapshot.imported.ageSecretKey)

                    // 对于本地文件配置文件，配置已被调用者复制到 stagingDir 中。
                    // 跳过 fetch (force=false) 并让本机代码直接验证现有的 config.yaml。
                    val isLocalFile = snapshot.imported.type == Profile.Type.File && snapshot.imported.source.startsWith("content://")

                    Clash.fetchAndValid(stagingDir, snapshot.imported.source, !isLocalFile) {
                            val fetchedSubInfo = it.toSubscriptionInfo()
                            if (fetchedSubInfo != null) {
                                subInfo = fetchedSubInfo
                                return@fetchAndValid
                            }

                            try {
                                cb?.updateStatus(it)
                            } catch (error: Exception) {
                                // fault barrier: the observer may live across a binder; reporting
                                // failures must not abort the profile fetch itself.
                                cb = null
                                Timber.w(error, "Report fetch status: %s", error.message)
                            }
                        }
                        .await()

                    profileLock.withLock {
                        if (ImportedDao.exists(snapshot.imported.uuid)) {
                            // 原子交换：将旧文件重命名为备份，将暂存文件重命名为目标文件。
                            // 如果进程在操作过程中终止，启动恢复将还原 .bak 文件。
                            val backupDir = context.importedDir.resolve("${uuid}.bak")
                            backupDir.deleteRecursively()
                            if (targetDir.exists()) {
                                moveDirectory(targetDir, backupDir)
                            }
                            moveDirectory(stagingDir, targetDir)
                            backupDir.deleteRecursively()

                            val finalName =
                                if (snapshot.imported.type == Profile.Type.Url) {
                                    resolveSubscriptionName(
                                        snapshot.imported.name,
                                        snapshot.imported.source,
                                        subInfo,
                                    )
                                } else {
                                    snapshot.imported.name
                                }

                            val updated =
                                Imported(
                                    snapshot.imported.uuid,
                                    finalName,
                                    snapshot.imported.type,
                                    snapshot.imported.source,
                                    subInfo?.updateInterval ?: snapshot.imported.interval,
                                    subInfo?.upload ?: snapshot.imported.upload,
                                    subInfo?.download ?: snapshot.imported.download,
                                    subInfo?.total ?: snapshot.imported.total,
                                    subInfo?.expire ?: snapshot.imported.expire,
                                    snapshot.imported.createdAt,
                                    ageSecretKey = snapshot.imported.ageSecretKey,
                                )
                            ImportedDao.update(updated)

                            AutoUpdate.replace(
                                context,
                                snapshot.imported.uuid,
                                updated.interval,
                            )
                            context.sendProfileChanged(snapshot.imported.uuid)
                        }
                    }
                } catch (error: Exception) {
                    // fault barrier: core fetch runs through the JNI bridge; roll back the staged update atomically, then rethrow (with a friendlier message for age errors).
                    profileLock.withLock {
                        if (
                            !snapshot.hasCommittedConfig &&
                                ImportedDao.exists(snapshot.imported.uuid)
                        ) {
                            ImportedDao.remove(snapshot.imported.uuid)
                            SelectionDao.clear(snapshot.imported.uuid)
                            targetDir.deleteRecursively()
                            context.sendProfileChanged(snapshot.imported.uuid)
                        } else if (ImportedDao.exists(snapshot.imported.uuid)) {
                            // Restore from .bak if atomic swap left orphaned backup
                            val backupDir =
                                context.importedDir.resolve("${uuid}.bak")
                            if (backupDir.exists() && !targetDir.exists()) {
                                moveDirectory(backupDir, targetDir)
                            }
                            backupDir.deleteRecursively()
                        }
                    }
                    // 为Age解密失败提供更加用户友好型的错误消息
                    val errorMessage = error.message ?: ""
                    if (
                        errorMessage.contains("no identities specified") ||
                            errorMessage.contains("decrypt config error")
                    ) {
                        throw IllegalArgumentException(
                            "This config is encrypted with age. Please provide the age secret key when importing the config.",
                            error,
                        )
                    } else {
                        throw error
                    }
                } finally {
                    stagingDir.deleteRecursively()
                }
            }
        }
    }

    // 将[源文件]移动到[目标位置]，当[File.renameTo]静默失败时（例如在某些Android设备跨文件系统挂载点操作时），回退使用复制+删除的方式。
    private fun moveDirectory(source: File, target: File) {
        if (source.renameTo(target)) return
        // "renameTo 返回 false — 则回退到递归复制"
        target.deleteRecursively()
        source.copyRecursively(target, overwrite = true)
        source.deleteRecursively()
    }

    suspend fun delete(context: Context, uuid: UUID) {
        withContext(Dispatchers.IO + NonCancellable) {
            profileLock.withLock {
                ImportedDao.remove(uuid)
                SelectionDao.clear(uuid)

                val imported = context.importedDir.resolve(uuid.toString())
                imported.deleteRecursively()

                context.sendProfileChanged(uuid)
            }
        }
    }

    suspend fun active(context: Context, uuid: UUID) {
        withContext(Dispatchers.IO + NonCancellable) {
            profileLock.withLock {
                if (!ImportedDao.exists(uuid)) {
                    throw IllegalArgumentException("profile $uuid is not available")
                }
                val store = ServiceStore()
                store.activeProfile = uuid
                context.sendProfileChanged(uuid)
            }
        }
    }

    /**
     * 基于WorkManager的定期订阅自动更新。
     * 每个配置了 `interval ≥ [MIN_INTERVAL_SECONDS]` 的URL配置文件都会创建一个独立的周期性工作条目。
     */
    object AutoUpdate {
        const val MIN_INTERVAL_SECONDS = 15 * 60L
        private const val TAG = "ProfileAutoUpdate"

        fun schedule(context: Context, uuid: UUID, intervalSeconds: Long) {
            if (intervalSeconds < MIN_INTERVAL_SECONDS) {
                cancel(context, uuid)
                return
            }
            enqueue(context, uuid, intervalSeconds, ExistingPeriodicWorkPolicy.KEEP)
        }

        fun replace(context: Context, uuid: UUID, intervalSeconds: Long) {
            if (intervalSeconds < MIN_INTERVAL_SECONDS) {
                cancel(context, uuid)
                return
            }
            enqueue(context, uuid, intervalSeconds, ExistingPeriodicWorkPolicy.UPDATE)
        }

        fun cancel(context: Context, uuid: UUID) {
            WorkManager.getInstance(context).cancelUniqueWork(workName(uuid))
            Timber.tag(TAG).i("Cancelled auto-update for $uuid")
        }

        /**在应用启动时同步所有URL配置文件。**/
        fun scheduleAll(context: Context) {
            val profiles = ImportedDao.queryAll()
            var scheduled = 0
            for (imported in profiles) {
                if (imported.type != Profile.Type.Url) continue
                if (imported.interval >= MIN_INTERVAL_SECONDS) {
                    schedule(context, imported.uuid, imported.interval)
                    scheduled++
                }
            }
            Timber.tag(TAG).i("scheduleAll: $scheduled profiles scheduled out of ${profiles.size}")
        }

        private fun enqueue(
            context: Context,
            uuid: UUID,
            intervalSeconds: Long,
            policy: ExistingPeriodicWorkPolicy,
        ) {
            val inputData = Data.Builder()
                .putString(ProfileAutoUpdateWorker.KEY_PROFILE_UUID, uuid.toString())
                .build()
            val constraints = Constraints.Builder()
                .setRequiredNetworkType(NetworkType.CONNECTED)
                .build()
            val request = PeriodicWorkRequestBuilder<ProfileAutoUpdateWorker>(
                repeatInterval = intervalSeconds,
                repeatIntervalTimeUnit = TimeUnit.SECONDS,
            )
                .setInputData(inputData)
                .setConstraints(constraints)
                .addTag("profile_update")
                .addTag("profile_update_$uuid")
                .build()
            WorkManager.getInstance(context)
                .enqueueUniquePeriodicWork(workName(uuid), policy, request)
            Timber.tag(TAG).i("Scheduled auto-update for $uuid every ${intervalSeconds}s ($policy)")
        }

        private fun workName(uuid: UUID): String = "profile_auto_update_$uuid"
    }
}

/**
 * 周期性更新单个订阅配置文件。
 * 由 [ProfileProcessor.AutoUpdate] 为每个 `间隔` ≥ 15 分钟的配置文件调度。
 */
class ProfileAutoUpdateWorker(
    appContext: Context,
    params: WorkerParameters,
) : CoroutineWorker(appContext, params) {

    override suspend fun doWork(): Result {
        val uuidStr = inputData.getString(KEY_PROFILE_UUID) ?: return Result.failure()
        val uuid = runCatching { UUID.fromString(uuidStr) }.getOrElse {
            Timber.tag(TAG).w("Invalid UUID in worker input: $uuidStr")
            return Result.failure()
        }
        val imported = ImportedDao.queryByUUID(uuid)
        if (imported == null) {
            Timber.tag(TAG).i("Profile $uuid no longer exists, cancelling update")
            return Result.failure()
        }
        if (imported.interval < ProfileProcessor.AutoUpdate.MIN_INTERVAL_SECONDS) {
            Timber.tag(TAG).i("Profile $uuid interval too short (${imported.interval}s), skipping")
            return Result.success()
        }
        return try {
            Timber.tag(TAG).i("Auto-updating profile: ${imported.name} ($uuid)")
            ProfileProcessor.update(applicationContext, uuid, null)
            Timber.tag(TAG).i("Auto-update complete: ${imported.name}")
            Result.success()
        } catch (error: Exception) {
            Timber.tag(TAG).w(error, "Auto-update failed for profile $uuid")
            Result.retry()
        }
    }

    companion object {
        private const val TAG = "ProfileAutoUpdate"
        const val KEY_PROFILE_UUID = "profile_uuid"
    }
}
